## Professor Shirley Cohen  ~  A. Jasim Azizi  ~  UTCS 327E - Databases
### TA:- Sameer, Karan

# Final Project - Milesonte One

#### Choose either MySQL or Postgres for your project and follow the appropriate setup guide (linked below) to deploy your environment on GCP: 
#### MySQL Server 8

### Set the Base Directory

In [1]:
%env BASE_DIR=/home/jupyter/Jasim/projects/final_project

env: BASE_DIR=/home/jupyter/Jasim/projects/final_project

### Download the load testing dataset from Google Cloud Storage:

In [3]:
!gsutil cp gs://cs327e-open-access/load_testing/us-500.zip .

Copying gs://cs327e-open-access/load_testing/us-500.zip...
/ [1 files][ 37.1 KiB/ 37.1 KiB]
Operation completed over 1 objects/37.1 KiB.

In [4]:
!gsutil cp gs://cs327e-open-access/load_testing/us-1000000.zip .

Copying gs://cs327e-open-access/load_testing/us-1000000.zip...
- [1 files][ 69.7 MiB/ 69.7 MiB]
Operation completed over 1 objects/69.7 MiB.

In [5]:
!unzip $BASE_DIR/us-500.zip

Archive:  /home/jupyter/Jasim/projects/final_project/us-500.zip
  inflating: us-500.csv

In [6]:
!unzip $BASE_DIR/us-1000000.zip

Archive:  /home/jupyter/Jasim/projects/final_project/us-1000000.zip
  inflating: us-1000000.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_us_500 = pd.read_csv('us-500.csv')
df_us_1000000 = pd.read_csv('us-1000000.csv')

In [5]:
df_us_500.head()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com

In [6]:
df_us_1000000.head()

,first_name,last_name,company_name,address,city,county,state,zip,phone1,phone2,email,web
0,James,Butt,"Benton, John B Jr",6649 N Blue Gum St,New Orleans,Orleans,LA,70116,504-621-8927,504-845-1427,jbutt@gmail.com,http://www.bentonjohnbjr.com
1,Josephine,Darakjy,"Chanay, Jeffrey A Esq",4 B Blue Ridge Blvd,Brighton,Livingston,MI,48116,810-292-9388,810-374-9840,josephine_darakjy@darakjy.org,http://www.chanayjeffreyaesq.com
2,Art,Venere,"Chemel, James L Cpa",8 W Cerritos Ave #54,Bridgeport,Gloucester,NJ,8014,856-636-8749,856-264-4130,art@venere.org,http://www.chemeljameslcpa.com
3,Lenna,Paprocki,Feltz Printing Service,639 Main St,Anchorage,Anchorage,AK,99501,907-385-4412,907-921-2010,lpaprocki@hotmail.com,http://www.feltzprintingservice.com
4,Donette,Foller,Printing Dimensions,34 Center St,Hamilton,Butler,OH,45011,513-570-1893,513-549-4561,donette.foller@cox.net,http://www.printingdimensions.com

In [4]:
print(df_us_1000000.columns)
print("\nTotal Entries:")
print(len(df_us_1000000))
# df_us_1000000.size

Index(['first_name', 'last_name', 'company_name', 'address', 'city', 'county',
       'state', 'zip', 'phone1', 'phone2', 'email', 'web'],
      dtype='object')

Total Entries:
1000000

#

### 4.  In a new Jupyter notebook named milestone1.ipynb, write some Python code to sample the character lengths of the fields in the sample file (us-500.csv). Your code  should scan the contents of the file and keep track of the max length of each column.

In [5]:
for col in df_us_500.columns:
    lengths = df_us_500[col].apply(lambda x: len(str(x)))
    print(col, lengths.max())

first_name 10
last_name 13
company_name 30
address 31
city 19
county 20
state 2
zip 5
phone1 12
phone2 12
email 34
web 42

### 5. Based on the results from the previous step, write the -DDL- to create the table.
### If you are using MySQL, include the logic to drop the database if it exists before creating it. Hint: review Project 1 if you don’t remember how to do this step. If you are using Postgres, include the logic to drop the schema and its constraints if they exist before creating them. 
### Hint: review Project 2 if you don’t remember how to do this step. The table should use VARCHAR types for all variable-length fields and CHAR types for regular length fields (e.g. zip code, phone number, etc.). For each VARCHAR field in the table, add 10 extra characters for padding. 
### For example, if the email field in the sample file has 34 characters, define the email field in the table as varchar(44). Define a Primary Key for the table using an auto-incremented field. Refer to the documentation for instructions on how to create the auto-incremented field (MySQL doc) (Postgres doc). Follow these naming conventions when writing the DDL script:

#### Database (mysql) ________ load_testing
#### Schema (postgres) _______ load_testing
#### Table ____________________ Person
#### Columns _________________ first_name, last_name, etc.
#### Primary Key _____________ id
#### DDL File _________________ create_table.sql

In [4]:
%env INSTANCE=mysql

env: INSTANCE=mysql

## MySQL is used in create_table.sql DDL file
### Data Definition Language (DDL) is a standard for commands that define the different structures in a database. DDL statements create, modify, and remove database objects such as tables, indexes, and users. Common DDL statements are CREATE, ALTER, and DROP.

In [31]:
!mysql < create_table.sql

In [32]:
!mysql load_testing -e "show tables"

+------------------------+
| Tables_in_load_testing |
+------------------------+
| Person                 |
+------------------------+

###


#### 6. In your Jupyter notebook, install the appropriate Python connector for your chosen system.
#### pip install mysql-connector-python (documentation)

In [14]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-8.0.29-cp37-cp37m-manylinux1_x86_64.whl (25.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.2/25.2 MB 105.3 kB/s eta 0:00:0000:0100:07
Requirement already satisfied: protobuf>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from mysql-connector-python) (3.19.4)
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.0.29
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /opt/conda/lib/python3.7/site-packages (8.0.29)
Requirement already satisfied: protobuf>=3.0.0 in /opt/conda/lib/python3.7/site-packages (from mysql-connector-python) (3.19.4)
Note: you may need to restart the kernel to use updated packages.

#### 7. In your Jupyter notebook, write the Python code that loads the contents of us-1000000.csv into the Person table. Skip the first line of the file as it contains only the column headings.

#### If you are using MySQL, use the connector’s execute() method to insert each row. See code sample for more details. Do not use the connector’s executemany() method as this will be one of the optimizations we try in Milestone 2.

#### Notice the try, except, finally blocks in the code sample, make sure to include those blocks in your solution. Issue a commit every 5000 rows and print the number of records successfully inserted into your table.

In [6]:
df_us_1000000 = pd.read_csv('us-1000000.csv')
print("Column", "\t \t \t \t", "Length \n")
for eachCol in df_us_1000000.columns:
    colLengths = df_us_1000000[eachCol].apply(lambda i: len(str(i)))
    print(eachCol, "\t \t \t ", colLengths.max())

Column 	 	 	 	 Length

first_name 	 	 	  11
last_name 	 	 	  13
company_name 	 	 	  30
address 	 	 	  37
city 	 	 	  22
county 	 	 	  21
state 	 	 	  2
zip 	 	 	  5
phone1 	 	 	  12
phone2 	 	 	  12
email 	 	 	  43
web 	 	 	  44

#

In [10]:
!mysql load_testing -e "truncate table Person"

### 7-Continued...

#### Use the %%timeit magic function to measure the total execution time of your code. This function executes the code block a total of 8 times and reports the average time across 7 runs.

##### Your code should produce the following output:
##### 5000 records inserted successfully into Person table
##### 10000 records inserted successfully into Person table
##### 15000 records inserted successfully into Person table
##### 20000 records inserted successfully into Person table
##### 25000 records inserted successfully into Person table
##### 30000 records inserted successfully into Person table
##### 35000 records inserted successfully into Person table
##### ...
##### 1000000 records inserted successfully into Person table
##### MySQL/Postgres connection is closed
##### 4min 45s ± 19.6 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
##### Note that your %%timeit results may differ from those reported here.

In [14]:
%%timeit

import mysql.connector

# connecting to mysql DB
connection = mysql.connector.connect(
  host="10.128.0.3",
  user="root",
  password="data",
  database="load_testing",
  autocommit=False
)

print("Connection to MySQL \t ", connection)
print("\n")

sqlData = "INSERT INTO Person (first_name, last_name, company_name, address, city, county, state, zip, phone1, phone2, email, web)\
	  VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"

# to keep track of the cursor
counterCursor = 0

# Per question, as commented above
# TRY
try:
    for n, row in df_us_1000000.iterrows():
        
        record = (row['first_name'], row['last_name'], row['company_name'], row['address'], row['city'],\
               row['county'], row['state'], row['zip'], row['phone1'], row['phone2'], row['email'], row['web'])
        cursor = connection.cursor()
        cursor.execute(sqlData, record)
        counterCursor += cursor.rowcount
        
        if (n + 1) % 5000 == 0:
            connection.commit()
            print(counterCursor, "records inserted successfully into Person table")
            cursor.close()
# EXCEPT
except mysql.connector.Error as error:
    print("Unsuccessful to insert record(s) into Person table {}".format(error))
       
# FINALLY        
finally:
    if connection.is_connected():
        connection.close()
        print("MySQL connection is closed")

Connection to MySQL 	  <mysql.connector.connection_cext.CMySQLConnection object at 0x7f0d22c33d50>


5000 records inserted successfully into Person table
10000 records inserted successfully into Person table
15000 records inserted successfully into Person table
20000 records inserted successfully into Person table
25000 records inserted successfully into Person table
30000 records inserted successfully into Person table
35000 records inserted successfully into Person table
40000 records inserted successfully into Person table
45000 records inserted successfully into Person table
50000 records inserted successfully into Person table
55000 records inserted successfully into Person table
60000 records inserted successfully into Person table
65000 records inserted successfully into Person table
70000 records inserted successfully into Person table
75000 records inserted successfully into Person table
80000 records inserted successfully into Person table
85000 records inserted successfully into Person table
90000 records inserted successfully into Person table
95000 records inserted successfully into Person table
100000 records inserted successfully into Person table
105000 records inserted successfully into Person table
110000 records inserted successfully into Person table
115000 records inserted successfully into Person table
120000 records inserted successfully into Person table
125000 records inserted successfully into Person table
130000 records inserted successfully into Person table
135000 records inserted successfully into Person table
140000 records inserted successfully into Person table
145000 records inserted successfully into Person table
150000 records inserted successfully into Person table
155000 records inserted successfully into Person table
160000 records inserted successfully into Person table
165000 records inserted successfully into Person table
170000 records inserted successfully into Person table
175000 records inserted successfully into Person table
180000 records inserted successfully into Person table
185000 records inserted successfully into Person table
190000 records inserted successfully into Person table
195000 records inserted successfully into Person table
200000 records inserted successfully into Person table
205000 records inserted successfully into Person table
210000 records inserted successfully into Person table
215000 records inserted successfully into Person table
220000 records inserted successfully into Person table
225000 records inserted successfully into Person table
230000 records inserted successfully into Person table
235000 records inserted successfully into Person table
240000 records inserted successfully into Person table
245000 records inserted successfully into Person table
250000 records inserted successfully into Person table
255000 records inserted successfully into Person table
260000 records inserted successfully into Person table
265000 records inserted successfully into Person table
270000 records inserted successfully into Person table
275000 records inserted successfully into Person table
280000 records inserted successfully into Person table
285000 records inserted successfully into Person table
290000 records inserted successfully into Person table
295000 records inserted successfully into Person table
300000 records inserted successfully into Person table
305000 records inserted successfully into Person table
310000 records inserted successfully into Person table
315000 records inserted successfully into Person table
320000 records inserted successfully into Person table
325000 records inserted successfully into Person table
330000 records inserted successfully into Person table
335000 records inserted successfully into Person table
340000 records inserted successfully into Person table
345000 records inserted successfully into Person table
350000 records inserted successfully into Person table
355000 records inserted successfully into Person table
360000 records inserted successfully into Person table
365000 records inserted successfully into Person table
370000 records inserted successfully into Person table
375000 records inserted successfully into Person table
380000 records inserted successfully into Person table
385000 records inserted successfully into Person table
390000 records inserted successfully into Person table
395000 records inserted successfully into Person table
400000 records inserted successfully into Person table
405000 records inserted successfully into Person table
410000 records inserted successfully into Person table
415000 records inserted successfully into Person table
420000 records inserted successfully into Person table
425000 records inserted successfully into Person table
430000 records inserted successfully into Person table
435000 records inserted successfully into Person table
440000 records inserted successfully into Person table
445000 records inserted successfully into Person table
450000 records inserted successfully into Person table
455000 records inserted successfully into Person table
460000 records inserted successfully into Person table
465000 records inserted successfully into Person table
470000 records inserted successfully into Person table
475000 records inserted successfully into Person table
480000 records inserted successfully into Person table
485000 records inserted successfully into Person table
490000 records inserted successfully into Person table
495000 records inserted successfully into Person table
500000 records inserted successfully into Person table
505000 records inserted successfully into Person table
510000 records inserted successfully into Person table
515000 records inserted successfully into Person table
520000 records inserted successfully into Person table
525000 records inserted successfully into Person table
530000 records inserted successfully into Person table
535000 records inserted successfully into Person table
540000 records inserted successfully into Person table
545000 records inserted successfully into Person table
550000 records inserted successfully into Person table
555000 records inserted successfully into Person table
560000 records inserted successfully into Person table
565000 records inserted successfully into Person table
570000 records inserted successfully into Person table
575000 records inserted successfully into Person table
580000 records inserted successfully into Person table
585000 records inserted successfully into Person table
590000 records inserted successfully into Person table
595000 records inserted successfully into Person table
600000 records inserted successfully into Person table
605000 records inserted successfully into Person table
610000 records inserted successfully into Person table
615000 records inserted successfully into Person table
620000 records inserted successfully into Person table
625000 records inserted successfully into Person table
630000 records inserted successfully into Person table
635000 records inserted successfully into Person table
640000 records inserted successfully into Person table
645000 records inserted successfully into Person table
650000 records inserted successfully into Person table
655000 records inserted successfully into Person table
660000 records inserted successfully into Person table
665000 records inserted successfully into Person table
670000 records inserted successfully into Person table
675000 records inserted successfully into Person table
680000 records inserted successfully into Person table
685000 records inserted successfully into Person table
690000 records inserted successfully into Person table
695000 records inserted successfully into Person table
700000 records inserted successfully into Person table
705000 records inserted successfully into Person table
710000 records inserted successfully into Person table
715000 records inserted successfully into Person table
720000 records inserted successfully into Person table
725000 records inserted successfully into Person table
730000 records inserted successfully into Person table
735000 records inserted successfully into Person table
740000 records inserted successfully into Person table
745000 records inserted successfully into Person table
750000 records inserted successfully into Person table
755000 records inserted successfully into Person table
760000 records inserted successfully into Person table
765000 records inserted successfully into Person table
770000 records inserted successfully into Person table
775000 records inserted successfully into Person table
780000 records inserted successfully into Person table
785000 records inserted successfully into Person table
790000 records inserted successfully into Person table
795000 records inserted successfully into Person table
800000 records inserted successfully into Person table
805000 records inserted successfully into Person table
810000 records inserted successfully into Person table
815000 records inserted successfully into Person table
820000 records inserted successfully into Person table
825000 records inserted successfully into Person table
830000 records inserted successfully into Person table
835000 records inserted successfully into Person table
840000 records inserted successfully into Person table
845000 records inserted successfully into Person table
850000 records inserted successfully into Person table
855000 records inserted successfully into Person table
860000 records inserted successfully into Person table
865000 records inserted successfully into Person table
870000 records inserted successfully into Person table
875000 records inserted successfully into Person table
880000 records inserted successfully into Person table
885000 records inserted successfully into Person table
890000 records inserted successfully into Person table
895000 records inserted successfully into Person table
900000 records inserted successfully into Person table
905000 records inserted successfully into Person table
910000 records inserted successfully into Person table
915000 records inserted successfully into Person table
920000 records inserted successfully into Person table
925000 records inserted successfully into Person table
930000 records inserted successfully into Person table
935000 records inserted successfully into Person table
940000 records inserted successfully into Person table
945000 records inserted successfully into Person table
950000 records inserted successfully into Person table
955000 records inserted successfully into Person table
960000 records inserted successfully into Person table
965000 records inserted successfully into Person table
970000 records inserted successfully into Person table
975000 records inserted successfully into Person table
980000 records inserted successfully into Person table
985000 records inserted successfully into Person table
990000 records inserted successfully into Person table
995000 records inserted successfully into Person table
1000000 records inserted successfully into Person table
MySQL connection is closed
Connection to MySQL 	  <mysql.connector.connection_cext.CMySQLConnection object at 0x7f0d22465150>


5000 records inserted successfully into Person table
10000 records inserted successfully into Person table
15000 records inserted successfully into Person table
20000 records inserted successfully into Person table
25000 records inserted successfully into Person table
30000 records inserted successfully into Person table
35000 records inserted successfully into Person table
40000 records inserted successfully into Person table
45000 records inserted successfully into Person table
50000 records inserted successfully into Person table
55000 records inserted successfully into Person table
60000 records inserted successfully into Person table
65000 records inserted successfully into Person table
70000 records inserted successfully into Person table
75000 records inserted successfully into Person table
80000 records inserted successfully into Person table
85000 records inserted successfully into Person table
90000 records inserted successfully into Person table
95000 records inserted successfully into Person table
100000 records inserted successfully into Person table
105000 records inserted successfully into Person table
110000 records inserted successfully into Person table
115000 records inserted successfully into Person table
120000 records inserted successfully into Person table
125000 records inserted successfully into Person table
130000 records inserted successfully into Person table
135000 records inserted successfully into Person table
140000 records inserted successfully into Person table
145000 records inserted successfully into Person table
150000 records inserted successfully into Person table
155000 records inserted successfully into Person table
160000 records inserted successfully into Person table
165000 records inserted successfully into Person table
170000 records inserted successfully into Person table
175000 records inserted successfully into Person table
180000 records inserted successfully into Person table
185000 records inserted successfully into Person table
190000 records inserted successfully into Person table
195000 records inserted successfully into Person table
200000 records inserted successfully into Person table
205000 records inserted successfully into Person table
210000 records inserted successfully into Person table
215000 records inserted successfully into Person table
220000 records inserted successfully into Person table
225000 records inserted successfully into Person table
230000 records inserted successfully into Person table
235000 records inserted successfully into Person table
240000 records inserted successfully into Person table
245000 records inserted successfully into Person table
250000 records inserted successfully into Person table
255000 records inserted successfully into Person table
260000 records inserted successfully into Person table
265000 records inserted successfully into Person table
270000 records inserted successfully into Person table
275000 records inserted successfully into Person table
280000 records inserted successfully into Person table
285000 records inserted successfully into Person table
290000 records inserted successfully into Person table
295000 records inserted successfully into Person table
300000 records inserted successfully into Person table
305000 records inserted successfully into Person table
310000 records inserted successfully into Person table
315000 records inserted successfully into Person table
320000 records inserted successfully into Person table
325000 records inserted successfully into Person table
330000 records inserted successfully into Person table
335000 records inserted successfully into Person table
340000 records inserted successfully into Person table
345000 records inserted successfully into Person table
350000 records inserted successfully into Person table
355000 records inserted successfully into Person table
360000 records inserted successfully into Person table
365000 records inserted successfully into Person table
370000 records inserted successfully into Person table
375000 records inserted successfully into Person table
380000 records inserted successfully into Person table
385000 records inserted successfully into Person table
390000 records inserted successfully into Person table
395000 records inserted successfully into Person table
400000 records inserted successfully into Person table
405000 records inserted successfully into Person table
410000 records inserted successfully into Person table
415000 records inserted successfully into Person table
420000 records inserted successfully into Person table
425000 records inserted successfully into Person table
430000 records inserted successfully into Person table
435000 records inserted successfully into Person table
440000 records inserted successfully into Person table
445000 records inserted successfully into Person table
450000 records inserted successfully into Person table
455000 records inserted successfully into Person table
460000 records inserted successfully into Person table
465000 records inserted successfully into Person table
470000 records inserted successfully into Person table
475000 records inserted successfully into Person table
480000 records inserted successfully into Person table
485000 records inserted successfully into Person table
490000 records inserted successfully into Person table
495000 records inserted successfully into Person table
500000 records inserted successfully into Person table
505000 records inserted successfully into Person table
510000 records inserted successfully into Person table
515000 records inserted successfully into Person table
520000 records inserted successfully into Person table
525000 records inserted successfully into Person table
530000 records inserted successfully into Person table
535000 records inserted successfully into Person table
540000 records inserted successfully into Person table
545000 records inserted successfully into Person table
550000 records inserted successfully into Person table
555000 records inserted successfully into Person table
560000 records inserted successfully into Person table
565000 records inserted successfully into Person table
570000 records inserted successfully into Person table
575000 records inserted successfully into Person table
580000 records inserted successfully into Person table
585000 records inserted successfully into Person table
590000 records inserted successfully into Person table
595000 records inserted successfully into Person table
600000 records inserted successfully into Person table
605000 records inserted successfully into Person table
610000 records inserted successfully into Person table
615000 records inserted successfully into Person table
620000 records inserted successfully into Person table
625000 records inserted successfully into Person table
630000 records inserted successfully into Person table
635000 records inserted successfully into Person table
640000 records inserted successfully into Person table
645000 records inserted successfully into Person table
650000 records inserted successfully into Person table
655000 records inserted successfully into Person table
660000 records inserted successfully into Person table
665000 records inserted successfully into Person table
670000 records inserted successfully into Person table
675000 records inserted successfully into Person table
680000 records inserted successfully into Person table
685000 records inserted successfully into Person table
690000 records inserted successfully into Person table
695000 records inserted successfully into Person table
700000 records inserted successfully into Person table
705000 records inserted successfully into Person table
710000 records inserted successfully into Person table
715000 records inserted successfully into Person table
720000 records inserted successfully into Person table
725000 records inserted successfully into Person table
730000 records inserted successfully into Person table
735000 records inserted successfully into Person table
740000 records inserted successfully into Person table
745000 records inserted successfully into Person table
750000 records inserted successfully into Person table
755000 records inserted successfully into Person table
760000 records inserted successfully into Person table
765000 records inserted successfully into Person table
770000 records inserted successfully into Person table
775000 records inserted successfully into Person table
780000 records inserted successfully into Person table
785000 records inserted successfully into Person table
790000 records inserted successfully into Person table
795000 records inserted successfully into Person table
800000 records inserted successfully into Person table

####

#### 8. Query the Person table to get the record count. You should end up with exactly 8,000,000 records in the table after loading the us-1000000.csv file under the %%timeit function. If you have only 7,999,992 rows, you may be missing the last line of the file.

In [15]:
!mysql load_testing -e "select count(*) from Person"

+----------+
| count(*) |
+----------+
|  8000000 |
+----------+

##

## THE END